FROM ghcr.io/astral-sh/uv:0.8.14 AS uv

FROM python:3.12-slim
COPY --from=uv /uv /uvx /bin/
WORKDIR /app
COPY pyproject.toml uv.lock README.md ./
RUN uv sync --frozen --no-dev
COPY indexer/ indexer/
COPY lens_common/ lens_common/
ENTRYPOINT ["uv", "run", "--no-sync", "python", "-m", "indexer"]
